spring:
  application:
    name: game-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      max-block-ms: 60000
      delivery-timeout-ms: 120000

app:
  kafka:
    topic: game-events

server:
  port: 8080

logging:
  level:
    org.springframework.kafka: INFO
    io.gaming.platform.gameservice: DEBUG 